
CC	  = arm-elf-gcc
AS	  = arm-elf-as
LD	  = arm-elf-ld
OBJCOPY = arm-elf-objcopy

OBJDIR  = obj

INCLUDE = -I.

INCLUDES = at91sam7sXXX.h

CFLAGS  = -g -c $(INCLUDE) -Wall

OBJJTAG = $(OBJDIR)/bootrom.o $(OBJDIR)/ram-reset.o $(OBJDIR)/usb.o

OBJFLASH = $(OBJDIR)/flash-reset.o $(OBJDIR)/fromflash.o

all: forjtag.s19 bootrom.s19

$(OBJDIR)/bootrom.s19: $(OBJFLASH)
	@echo obj/bootrom.s19
	@$(LD) -g -Tldscript-flash --oformat elf32-littlearm -o $(OBJDIR)/bootrom.elf $(OBJFLASH)
	@$(OBJCOPY) -Osrec --srec-forceS3 $(OBJDIR)/bootrom.elf $(OBJDIR)/bootrom.s19

bootrom.s19: $(OBJDIR)/bootrom.s19 $(OBJDIR)/bootrom-forjtag.s19
	@echo bootrom.s19
	@perl merge-srec.pl $(OBJDIR)/bootrom.s19 $(OBJDIR)/bootrom-forjtag.s19 > bootrom.s19

$(OBJDIR)/bootrom-forjtag.s19: $(OBJJTAG)
	@echo obj/bootrom-forjtag.s19
	@$(LD) -g -Tldscript-ram-jtag --oformat elf32-littlearm -o $(OBJDIR)/bootrom-forjtag.elf $(OBJJTAG)
	@$(OBJCOPY) -Osrec --srec-forceS3 $(OBJDIR)/bootrom-forjtag.elf $(OBJDIR)/bootrom-forjtag.s19

forjtag.s19: $(OBJDIR)/bootrom-forjtag.s19
	@echo forjtag.s19
	@cat $(OBJDIR)/bootrom-forjtag.s19 > forjtag.s19
	@echo forjtag-swapped.s19
	@perl srecswap.pl $(OBJDIR)/bootrom-forjtag.s19 > forjtag-swapped.s19

$(OBJDIR)/bootrom.o: bootrom.c $(INCLUDES)
	@echo $(@B).c
	@$(CC) $(CFLAGS) -mthumb -mthumb-interwork bootrom.c -o $(OBJDIR)/bootrom.o

$(OBJDIR)/fromflash.o: fromflash.c $(INCLUDES)
	@echo $(@B).c
	@$(CC) $(CFLAGS) -mthumb -mthumb-interwork fromflash.c -o $(OBJDIR)/fromflash.o

$(OBJDIR)/usb.o: usb.c $(INCLUDES)
	@echo $(@B).c
	@$(CC) $(CFLAGS) -mthumb -mthumb-interwork usb.c -o $(OBJDIR)/usb.o

$(OBJDIR)/ram-reset.o: ram-reset.s
	@echo $(@B).s
	@$(CC) $(CFLAGS) -mthumb-interwork -o $(OBJDIR)/ram-reset.o ram-reset.s

$(OBJDIR)/flash-reset.o: flash-reset.s
	@echo $(@B).s
	@$(CC) $(CFLAGS) -mthumb-interwork -o $(OBJDIR)/flash-reset.o flash-reset.s

clean:
	del /q obj\*.o
	del /q obj\*.elf
	del /q obj\*.s19
	del /q *.s19
